version: "2"
services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    #environment:
      #- NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
